#!/bin/bash

source env/bin/activate

echo "Running black..."
black --exclude env . --line-length 120
echo "Running isort..."
isort . -s env
echo "Fixing implicit optional..."
no_implicit_optional crashlink
echo "Generating docs..."
pdoc3 crashlink --html -o docs --force --template-dir docs/templates
echo "Checking code quality..."
mypy crashlink
radon cc crashlink
pytest -lvv