@echo off

echo Running black...
env\Scripts\black --exclude env . --line-length 120
echo Running isort...
env\Scripts\isort . -s env
echo Fixing implicit optional...
env\Scripts\no_implicit_optional crashlink
echo Generating docs...
env\Scripts\pdoc3 crashlink --html -o docs --force --template-dir docs/templates
echo Checking code quality...
env\Scripts\mypy --strict --check-untyped-defs crashlink
env\Scripts\radon cc crashlink
env\Scripts\pytest