[project]
name = "crashlink"
version = "0.0.8"
authors = [
  { name="N3rdL0rd", email="n3rdl0rd@proton.me" },
]
description = "Just another HashLink decompiler/disassembler."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Disassemblers",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]
license = "MIT"
dependencies = []

[project.optional-dependencies]
dev = [
  "pdoc3",
  "ty",
  "pytest",
  "tqdm",
  "pytest-xdist",
  "staticjinja",
  "IPython",
  "requests",
  "ruff",
  "pygments",
  "markupsafe",
  "lief",
  "capstone",
  "mcp",
  "PySide6",
  "graphviz",
  "keystone-engine",
]
extras = [
  "tqdm",
  "IPython",
  "pygments",
  "lief",
  "capstone",
  "mcp",
  "PySide6",
  "graphviz",
  "keystone-engine",
]
gui = [
  "PySide6",
  "graphviz",
]

[build-system]
requires = ["uv_build>=0.9,<0.10"]
build-backend = "uv_build"

[project.scripts]
crashlink = "crashlink.__main__:main"
crashtest = "crashtest.__main__:main"

[tool.uv.build-backend]
module-name = ["crashlink", "crashtest", "hlrun"]
module-root = ""
source-exclude = ["/crashtest/runs", "/tests", "/local", "/env", "/pyhl"]
wheel-exclude = ["/crashtest/runs"]
