"""Members of Haxe std types that source outside the type cannot name: `type path ->
members` (fields and methods declared without `public`, in a class or abstract that doesn't
make every member public).

Generated from Haxe's std (`std/hl`, `std/hl/_std`).
"""

from typing import Dict, FrozenSet

PRIVATE_STD_MEMBERS: Dict[str, FrozenSet[str]] = {
    "Date": frozenset(
        {
            "date_from_string",
            "date_from_time",
            "date_get_inf",
            "date_get_time",
            "date_get_utc_inf",
            "date_new",
            "date_now",
            "date_to_string",
            "fromInt",
            "t",
        }
    ),
    "EReg": frozenset(
        {
            "escapeRegExpRe",
            "global",
            "last",
            "len",
            "p",
            "r",
            "regexp_match",
            "regexp_matched_pos",
            "regexp_new_options",
        }
    ),
    "Reflect": frozenset({"_makeVarArgs", "getObjectFields"}),
    "Std": frozenset({"__add__", "__init__", "rnd", "rnd_float", "rnd_int", "rnd_sys", "toStringDepth"}),
    "String": frozenset(
        {
            "__add__",
            "__alloc__",
            "__compare",
            "__string",
            "bytes",
            "call_toString",
            "findChar",
            "fromUCS2",
            "fromUTF8",
            "toUtf8",
        }
    ),
    "StringBuf": frozenset({"__add", "__expand", "b", "get_length", "pos", "size"}),
    "Sys": frozenset(
        {
            "__init__",
            "file_stderr",
            "file_stdin",
            "file_stdout",
            "getPath",
            "get_cwd",
            "get_env",
            "makePath",
            "put_env",
            "set_cwd",
            "set_time_locale",
            "sys_args",
            "sys_command",
            "sys_env",
            "sys_exe_path",
            "sys_hl_file",
            "sys_print",
            "sys_program_path",
            "sys_string",
            "sys_utf8_path",
            "utf8Path",
        }
    ),
    "Type": frozenset(
        {"_enumParameters", "allTypes", "get_allTypes", "init", "initClass", "initEnum", "register"}
    ),
    "UInt": frozenset(
        {
            "add",
            "addWithFloat",
            "and",
            "div",
            "divFloat",
            "equalsFloat",
            "equalsInt",
            "floatDiv",
            "floatGt",
            "floatGte",
            "floatLt",
            "floatLte",
            "floatMod",
            "floatSub",
            "gt",
            "gtFloat",
            "gte",
            "gteFloat",
            "lt",
            "ltFloat",
            "lte",
            "lteFloat",
            "mod",
            "modFloat",
            "mul",
            "mulWithFloat",
            "negBits",
            "notEqualsFloat",
            "notEqualsInt",
            "or",
            "postfixDecrement",
            "postfixIncrement",
            "prefixDecrement",
            "prefixIncrement",
            "shl",
            "shr",
            "sub",
            "subFloat",
            "toFloat",
            "toInt",
            "toString",
            "ushr",
            "xor",
        }
    ),
    "haxe.Exception": frozenset(
        {
            "__exceptionMessage",
            "__exceptionStack",
            "__nativeException",
            "__nativeStack",
            "__previousException",
            "__shiftStack",
            "__skipStack",
            "__unshiftStack",
            "caught",
            "get_message",
            "get_native",
            "get_previous",
            "get_stack",
            "thrown",
            "unwrap",
        }
    ),
    "haxe.Int64": frozenset(
        {
            "MASK",
            "addInt",
            "complement",
            "divInt",
            "eqInt",
            "get_high",
            "get_low",
            "get_val",
            "intDiv",
            "intGte",
            "intMod",
            "intSub",
            "lt",
            "modInt",
            "mulInt",
            "neqInt",
            "new",
            "postDecrement",
            "postIncrement",
            "preDecrement",
            "preIncrement",
            "set_high",
            "set_low",
            "set_val",
            "subInt",
            "val",
        }
    ),
    "haxe.NativeStackTrace": frozenset({"callStackRaw", "exceptionStackRaw", "resolveSymbol"}),
    "haxe.Resource": frozenset({"__init__", "content"}),
    "haxe.ds.IntMap": frozenset({"h"}),
    "haxe.ds.StringMap": frozenset({"h"}),
    "haxe.ds.StringMap.StringMapKeysIterator": frozenset({"arr", "length", "pos"}),
    "haxe.ds.Vector": frozenset({"get_length"}),
    "haxe.io.Bytes": frozenset({"alignBuffer", "b", "new", "out", "outRange"}),
    "haxe.io.BytesBuffer": frozenset({"__add", "__expand", "b", "get_length", "pos", "size"}),
    "haxe.io.FPHelper": frozenset({"helper", "i64tmp"}),
    "haxe.zip.Compress": frozenset({"deflate_bound", "deflate_buffer", "deflate_init", "done", "read", "s"}),
    "haxe.zip.Uncompress": frozenset(
        {"done", "inflate_buffer", "inflate_init", "read", "s", "zip_end", "zip_flush_mode"}
    ),
    "hl.Bytes": frozenset(
        {"alloc", "from_address", "get_address", "hash", "ucs2Lower", "ucs2Upper", "urlDecode", "urlEncode"}
    ),
    "hl.BytesAccess": frozenset({"get_nullValue", "get_sizeBits"}),
    "hl.CArray": frozenset({"alloc_carray", "get", "getIndex", "getLen", "get_length"}),
    "hl.Format.Mikktspace": frozenset({"_compute"}),
    "hl.Gc": frozenset({"_dump", "_get_flags", "_set_flags", "_stats", "get_flags", "set_flags"}),
    "hl.I64": frozenset(
        {
            "add",
            "and",
            "compl",
            "decr",
            "div",
            "eq",
            "gt",
            "gte",
            "implicitToInt",
            "incr",
            "lt",
            "lte",
            "mod",
            "mul",
            "neg",
            "or",
            "pdecr",
            "pincr",
            "shl",
            "shr",
            "sub",
            "ushr",
            "xor",
        }
    ),
    "hl.NativeArray": frozenset({"get", "get_length", "set"}),
    "hl.NativeArray.NativeArrayIterator": frozenset({"arr", "length", "pos"}),
    "hl.NativeArray.NativeArrayKeyValueIterator": frozenset({"arr", "length", "pos"}),
    "hl.Profile": frozenset(
        {
            "BUFSIZE",
            "KINDS",
            "__init__",
            "buf",
            "get_globalBits",
            "get_threadBits",
            "resolveSymbol",
            "resolve_symbol",
            "set_globalBits",
            "set_threadBits",
            "sys_profile_event",
            "track_count",
            "track_entry",
            "track_get_bits",
            "track_init",
            "track_lock",
            "track_set_bits",
        }
    ),
    "hl.Type": frozenset({"getNameBytes", "get_kind"}),
    "hl.UI": frozenset(
        {"__init__", "_chooseFile", "_dialog", "_getClipboardText", "_setClipboardText", "chooseFile", "init"}
    ),
    "hl.UI.Button": frozenset({"button_new"}),
    "hl.UI.Sentinel": frozenset(
        {"_pause", "_tick", "create_sentinel", "get_pause", "is_paused", "set_pause"}
    ),
    "hl.UI.WinLog": frozenset({"winlog_new", "winlog_set_text"}),
    "hl.UI.Window": frozenset({"h", "win_destroy", "win_set_enable", "win_set_text"}),
    "hl.types.ArrayBase": frozenset({"__cast", "isArrayObj"}),
    "hl.types.ArrayBytes": frozenset({"__expand", "bytes", "size"}),
    "hl.types.ArrayBytes.BytesIterator": frozenset({"a"}),
    "hl.types.ArrayDyn": frozenset(
        {"__cast", "__compare", "__get_field", "allowReinterpret", "array", "get_length"}
    ),
    "hl.types.ArrayDyn.ArrayDynIterator": frozenset({"a"}),
    "hl.types.ArrayObj": frozenset({"__expand", "array"}),
    "hl.types.ArrayObj.ArrayObjIterator": frozenset({"arr"}),
    "hl.types.BytesMap": frozenset({"alloc"}),
    "hl.types.Int64Map": frozenset({"alloc"}),
    "hl.types.IntMap": frozenset({"alloc"}),
    "hl.types.ObjectMap": frozenset({"alloc"}),
    "hl.uv.Fs": frozenset({"fs_start_wrap", "fs_stop_wrap"}),
    "hl.uv.Handle": frozenset({"close_handle", "new"}),
    "hl.uv.Loop": frozenset({"default_loop", "loopEvent"}),
    "hl.uv.Stream": frozenset({"stream_listen", "stream_read_start", "stream_read_stop", "stream_write"}),
    "hl.uv.Tcp": frozenset(
        {"tcp_accept_wrap", "tcp_bind_wrap", "tcp_connect_wrap", "tcp_init_wrap", "tcp_nodelay_wrap"}
    ),
    "sys.FileSystem": frozenset(
        {
            "makeCompatiblePath",
            "sys_create_dir",
            "sys_delete",
            "sys_exists",
            "sys_full_path",
            "sys_is_dir",
            "sys_read_dir",
            "sys_remove_dir",
            "sys_rename",
            "sys_stat",
        }
    ),
    "sys.db.Mysql": frozenset({"INIT_DONE"}),
    "sys.db.Mysql.MysqlConnection": frozenset(
        {
            "close_wrap",
            "connect_wrap",
            "escape_wrap",
            "h",
            "new",
            "request_wrap",
            "select_db_wrap",
            "setConvFuns",
        }
    ),
    "sys.db.Mysql.MysqlResultSet": frozenset(
        {
            "cache",
            "get_length",
            "get_nfields",
            "new",
            "r",
            "result_get",
            "result_get_fields_names",
            "result_get_float",
            "result_get_int",
            "result_get_length",
            "result_get_nfields",
            "result_next",
        }
    ),
    "sys.db.Sqlite.SqliteConnection": frozenset({"c"}),
    "sys.db.Sqlite.SqliteResultSet": frozenset(
        {"cache", "doNext", "get_length", "get_nfields", "names", "r"}
    ),
    "sys.io.File": frozenset({"file_contents", "file_open"}),
    "sys.io.FileInput": frozenset(
        {"__f", "file_close", "file_eof", "file_read", "file_read_char", "file_seek", "file_tell", "new"}
    ),
    "sys.io.FileOutput": frozenset({"__f", "file_flush", "file_write", "file_write_char", "new"}),
    "sys.io.Process": frozenset({"_close", "_exit", "_kill", "_pid", "_run", "isWin", "p"}),
    "sys.io.Process.Stdin": frozenset({"_stdin_close", "_stdin_write", "buf", "p"}),
    "sys.io.Process.Stdout": frozenset({"_stderr_read", "_stdout_read", "buf", "out", "p"}),
    "sys.net.Host": frozenset({"host_local", "host_resolve", "host_reverse", "host_to_string"}),
    "sys.net.Socket": frozenset(
        {
            "__init__",
            "__s",
            "curTmpSize",
            "h",
            "init",
            "ip",
            "makeArray",
            "outArray",
            "socket_accept",
            "socket_bind",
            "socket_close",
            "socket_connect",
            "socket_fd_size",
            "socket_host",
            "socket_init",
            "socket_listen",
            "socket_new",
            "socket_peer",
            "socket_select",
            "socket_set_blocking",
            "socket_set_fast_send",
            "socket_set_timeout",
            "socket_shutdown",
            "sothers",
            "sread",
            "swrite",
            "tmp",
            "tmpSize",
        }
    ),
    "sys.net.Socket.SocketInput": frozenset({"sock", "socket_recv", "socket_recv_char"}),
    "sys.net.Socket.SocketOutput": frozenset({"sock", "socket_send", "socket_send_char"}),
    "sys.net.UdpSocket": frozenset({"socket_recv_from", "socket_send_to", "socket_set_broadcast"}),
    "sys.ssl.Certificate": frozenset(
        {
            "__h",
            "__x",
            "cert_add_der",
            "cert_add_pem",
            "cert_get_altnames",
            "cert_get_issuer",
            "cert_get_next",
            "cert_get_notafter",
            "cert_get_notbefore",
            "cert_get_subject",
            "cert_load_defaults",
            "cert_load_file",
            "cert_load_path",
            "get_altNames",
            "get_commonName",
            "get_notAfter",
            "get_notBefore",
            "new",
        }
    ),
    "sys.ssl.Context": frozenset({"ssl_new"}),
    "sys.ssl.Context.Config": frozenset({"conf_new"}),
    "sys.ssl.Digest": frozenset({"dgst_make", "dgst_sign", "dgst_verify"}),
    "sys.ssl.Key": frozenset({"__k", "key_from_der", "key_from_pem", "new"}),
    "sys.ssl.Lib": frozenset({"__init__", "ssl_init"}),
    "sys.ssl.Socket": frozenset(
        {
            "altSNIContexts",
            "buildConfig",
            "caCert",
            "conf",
            "handshakeDone",
            "hostname",
            "isBlocking",
            "ownCert",
            "ownKey",
            "sniCallback",
            "ssl",
        }
    ),
    "sys.ssl.Socket.SocketInput": frozenset({"__s"}),
    "sys.ssl.Socket.SocketOutput": frozenset({"__s"}),
    "sys.thread.Condition": frozenset({"alloc"}),
    "sys.thread.Deque": frozenset({"alloc"}),
    "sys.thread.Lock": frozenset({"deque", "handle", "lock_create", "lock_release", "lock_wait"}),
    "sys.thread.Semaphore": frozenset({"alloc"}),
    "sys.thread.Thread": frozenset({"get_events", "get_name", "set_name"}),
    "sys.thread.Thread.HaxeThread": frozenset(
        {
            "UID",
            "__init__",
            "createHandle",
            "currentHandle",
            "dropThread",
            "handle",
            "id",
            "mainThread",
            "threads",
            "threadsMutex",
        }
    ),
    "sys.thread.Tls": frozenset({"get_value", "set_value", "tls_alloc", "tls_get", "tls_set"}),
}
