HASHLINK_BIN = ./hashlink-bin
HASHLINK = ./hashlink-bin/include

PYTHON = ./include
PYTHON_LIB = ./python3.lib

DEFINES = /D Py_BUILD_CORE_MODULE

INCLUDE_FLAGS = /I . /I $(HASHLINK) /I $(PYTHON)

all: pyhl.hdll

pyhl.hdll: pyhl.obj
	cl /LD /MD /DEBUG:FULL pyhl.obj "$(HASHLINK_BIN)\libhl.lib" "$(PYTHON_LIB)" /VERBOSE:LIB

pyhl.obj: pyhl.c
	cl /c /MD /Zi /Fdpyhl.pdb $(DEFINES) pyhl.c $(INCLUDE_FLAGS)

check_lib:
	dumpbin /EXPORTS $(PYTHON_LIB)

.PHONY: all check_lib