"""
Decompilation, IR and control flow graph generation.

Sub-modules
-----------
cfg        Control-flow graph (CFNode, CFGraph, …)
ir         IR node classes (IRStatement, IRBlock, IRLocal, …)
opt        Optimizer base classes and sub-packages
function   Top-level orchestrators (IRFunction, IRClass)
"""

import sys

# IR statement/block reprs and some optimizer walks recurse once per nesting
# level (e.g. a deeply nested if/else chain, or a large lowered switch before
# IRIntSwitchOptimizer restructures it). Real-world dispatch tables/parsers can
# nest a few hundred levels deep, well past Python's default limit of 1000.
if sys.getrecursionlimit() < 8000:
    sys.setrecursionlimit(8000)

from .cfg import (
    CFNode,
    CFOptimizer,
    CFJumpThreader,
    CFDeadCodeEliminator,
    CFGraph,
    IsolatedCFGraph,
    _find_jumps_to_label,
)
from .ir import (
    _ANSI_ESCAPE_RE,
    _strip_ansi,
    _repr_rendered_blocks,
    _type_by_name_cache,
    _get_type_in_code,
    IRStatement,
    IRBlock,
    IRExpression,
    IRLocal,
    IRArithmetic,
    IRNeg,
    IRNot,
    IRTypeOf,
    IRTypeKind,
    IRAssign,
    IRCall,
    IRBoolExpr,
    IRConst,
    IRConditional,
    IRPrimitiveLoop,
    IRBreak,
    IRContinue,
    IRReturn,
    IRThrow,
    IRTrace,
    IRTryCatch,
    IRSwitch,
    IRPrimitiveJump,
    IRWhileLoop,
    IRForEachLoop,
    IRIntRangeLoop,
    IRField,
    IRBoundClosure,
    IRNew,
    IRNativeArrayNew,
    IRNativeMapNew,
    IRBytesNew,
    IRCast,
    IRArrayLiteral,
    IRObjectLiteral,
    IRArrayAccess,
    IRRef,
    IRRefNew,
    IRRefGet,
    IRRefSet,
    IREnumConstruct,
    IREnumIndex,
    IREnumField,
    IRUnliftedOpcode,
    IRNativeStub,
)
from .opt import (
    IROptimizer,
    TraversingIROptimizer,
    _ir_structurally_equal,
    _structurally_equal,
    _stmt_lists_structurally_equal,
    _bytes_mem_kind,
    _int_const_value,
    _signed_i32,
)
from .opt.inliner import (
    IRPrimitiveJumpLifter,
    IRConditionInliner,
    IRTempAssignmentInliner,
    IRCopyPropOptimizer,
)
from .opt.clean import (
    IRLoopConditionOptimizer,
    IRSelfAssignOptimizer,
    IRArrayGrowGuardEliminator,
    IRArrayObjBoundsCheckCollapser,
    IRRedundantRecomputeEliminator,
    IRBlockFlattener,
    IRCommonBlockMerger,
    IRRedundantContinueEliminator,
    IRVoidAssignOptimizer,
    IRDeadTempEliminator,
    IRDeadCodeEliminator,
    IRDeadStoreEliminator,
    IRSequentialTempFolder,
    IRDeadAssignmentEliminator,
    IRConstructorFolder,
    IREnumConstructorFolder,
    IRAnonObjectLiteralOptimizer,
    IRShiftConstantOptimizer,
    IRGuardOrMerger,
    IRTypedCatchOptimizer,
)
from .opt.strings import (
    IRGlobalStringOptimizer,
    IRStringIntConcatOptimizer,
    IRStringAllocOptimizer,
    IRTraceOptimizer,
    IRStringConcatFolder,
)
from .opt.arrays import (
    IRNativeArrayAllocOptimizer,
    IRArrayObjWrapperOptimizer,
    IRNativeMapAllocOptimizer,
    IRArrayPatternOptimizer,
)
from .opt.loops import (
    IRLoopRerollOptimizer,
    IRForEachLoopOptimizer,
    IRIntRangeLoopOptimizer,
)
from .opt.switches import (
    IRIntSwitchOptimizer,
    IRStringSwitchOptimizer,
    IREnumSwitchOptimizer,
)
from .function import (
    _build_enum_global_map,
    IRFunction,
    IRClass,
    STATIC_INIT_UNRECOVERABLE,
)

__all__ = [
    "CFDeadCodeEliminator",
    "CFGraph",
    "CFJumpThreader",
    "CFNode",
    "CFOptimizer",
    "IsolatedCFGraph",
    "IRArithmetic",
    "IRAssign",
    "IRAnonObjectLiteralOptimizer",
    "IRArrayAccess",
    "IRArrayGrowGuardEliminator",
    "IRArrayObjBoundsCheckCollapser",
    "IRArrayLiteral",
    "IRArrayObjWrapperOptimizer",
    "IRArrayPatternOptimizer",
    "IRBlock",
    "IRBlockFlattener",
    "IRBoolExpr",
    "IRBreak",
    "IRCall",
    "IRCast",
    "IRClass",
    "IRCommonBlockMerger",
    "IRConditionInliner",
    "IRConditional",
    "IRContinue",
    "IRConst",
    "IRConstructorFolder",
    "IREnumConstructorFolder",
    "IRCopyPropOptimizer",
    "IRDeadAssignmentEliminator",
    "IRDeadCodeEliminator",
    "IRDeadStoreEliminator",
    "IRDeadTempEliminator",
    "IREnumConstruct",
    "IREnumField",
    "IREnumIndex",
    "IREnumSwitchOptimizer",
    "IRExpression",
    "IRField",
    "IRBoundClosure",
    "IRForEachLoop",
    "IRForEachLoopOptimizer",
    "IRFunction",
    "IRGlobalStringOptimizer",
    "IRGuardOrMerger",
    "IRIntRangeLoop",
    "IRIntRangeLoopOptimizer",
    "IRIntSwitchOptimizer",
    "IRLocal",
    "IRLoopConditionOptimizer",
    "IRLoopRerollOptimizer",
    "IRNativeArrayNew",
    "IRNativeArrayAllocOptimizer",
    "IRNativeMapNew",
    "IRBytesNew",
    "IRNativeMapAllocOptimizer",
    "IRNativeStub",
    "IRNeg",
    "IRNew",
    "IRNot",
    "IRObjectLiteral",
    "IROptimizer",
    "IRPrimitiveJump",
    "IRPrimitiveJumpLifter",
    "IRPrimitiveLoop",
    "IRRedundantContinueEliminator",
    "IRRedundantRecomputeEliminator",
    "IRRef",
    "IRRefNew",
    "IRRefGet",
    "IRRefSet",
    "IRReturn",
    "IRSelfAssignOptimizer",
    "IRSequentialTempFolder",
    "IRShiftConstantOptimizer",
    "IRStatement",
    "IRStringAllocOptimizer",
    "IRStringConcatFolder",
    "IRStringIntConcatOptimizer",
    "IRStringSwitchOptimizer",
    "IRSwitch",
    "IRTempAssignmentInliner",
    "IRTrace",
    "IRTraceOptimizer",
    "IRTryCatch",
    "IRTypedCatchOptimizer",
    "IRThrow",
    "IRTypeKind",
    "IRTypeOf",
    "IRUnliftedOpcode",
    "IRVoidAssignOptimizer",
    "IRWhileLoop",
    "TraversingIROptimizer",
    "_get_type_in_code",
    "_strip_ansi",
    "_type_by_name_cache",
    "_repr_rendered_blocks",
]
